//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace PeachtreeBus.SourceGenerators.LoggerExtensions {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/LogMessages.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("Assembly", Namespace="http://tempuri.org/LogMessages.xsd", IsNullable=false)]
    public partial class AssemblyType {
        
        private string[] usingsField;
        
        private NamespaceType[] namespaceField;
        
        private int assemblyIdField;
        
        private bool exludeFromCodeCoverageField;
        
        private bool exludeFromCodeCoverageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Using", IsNullable=false)]
        public string[] Usings {
            get {
                return this.usingsField;
            }
            set {
                this.usingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Namespace")]
        public NamespaceType[] Namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int assemblyId {
            get {
                return this.assemblyIdField;
            }
            set {
                this.assemblyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool exludeFromCodeCoverage {
            get {
                return this.exludeFromCodeCoverageField;
            }
            set {
                this.exludeFromCodeCoverageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exludeFromCodeCoverageSpecified {
            get {
                return this.exludeFromCodeCoverageFieldSpecified;
            }
            set {
                this.exludeFromCodeCoverageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/LogMessages.xsd")]
    public partial class NamespaceType {
        
        private ClassType[] classField;
        
        private string nameField;
        
        private int namespaceIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Class")]
        public ClassType[] Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int namespaceId {
            get {
                return this.namespaceIdField;
            }
            set {
                this.namespaceIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/LogMessages.xsd")]
    public partial class ClassType {
        
        private EventType[] eventField;
        
        private string nameField;
        
        private int classIdField;
        
        private string genericArgsField;
        
        private string genericConstraintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Event")]
        public EventType[] Event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int classId {
            get {
                return this.classIdField;
            }
            set {
                this.classIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string genericArgs {
            get {
                return this.genericArgsField;
            }
            set {
                this.genericArgsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string genericConstraint {
            get {
                return this.genericConstraintField;
            }
            set {
                this.genericConstraintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/LogMessages.xsd")]
    public partial class EventType {
        
        private string nameField;
        
        private LevelType levelField;
        
        private bool levelFieldSpecified;
        
        private bool exceptionField;
        
        private bool exceptionFieldSpecified;
        
        private int eventIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public LevelType level {
            get {
                return this.levelField;
            }
            set {
                this.levelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool levelSpecified {
            get {
                return this.levelFieldSpecified;
            }
            set {
                this.levelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool exceptionSpecified {
            get {
                return this.exceptionFieldSpecified;
            }
            set {
                this.exceptionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int eventId {
            get {
                return this.eventIdField;
            }
            set {
                this.eventIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/LogMessages.xsd")]
    public enum LevelType {
        
        /// <remarks/>
        Trace,
        
        /// <remarks/>
        Debug,
        
        /// <remarks/>
        Information,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        None,
    }
}
