using PeachtreeBus.Data;
using PeachtreeBus.Queues;

namespace PeachtreeBus.Subscriptions;

/// <summary>
/// Represents a row in a subscription messages table.
/// </summary>
public class SubscribedData : QueueData
{
    /// <summary>
    /// The subscriber the message has been published for.
    /// Will be generated by the database when inserted.
    /// </summary>
    public virtual SubscriberId SubscriberId { get; set; }

    /// <summary>
    /// The time at which the message is considered abandonded
    /// and may be deleted.
    /// </summary>
    public required UtcDateTime ValidUntil { get; set; }

    public required Topic Topic { get; set; }
}
