CREATE TABLE [PeachtreeBus].[SagaData]
(
	[Id] BIGINT NOT NULL IDENTITY PRIMARY KEY,
	[SagaId] UNIQUEIDENTIFIER NOT NULL, 
	[Class] NVARCHAR(1024) NOT NULL,
	[Key] NVARCHAR(128) NOT NULL,
	[Data] NVARCHAR(MAX) NOT NULL,
	CONSTRAINT AK_SagaInstance UNIQUE([Class], [Key])
)
